language: python
python:
  - "3.6"
addons:
  hosts:
  - metadata.fragilefamilies.princeton.edu

install:
  - pip install -r requirements.txt
  - python ffmeta/scripts/populate_tables.py --quiet
script: py.test tests
