language: python
python:
  - "3.6"
addons:
  hosts:
  - metadata.fragilefamilies.princeton.edu

before_install:
  - mysql -e 'SOURCE ffmeta/data/ffmeta20181026.sql;'
install:
  - pip install -r requirements.txt
script: py.test tests
